<a href="https://colab.research.google.com/github/180030814-GnaneshwarReddy/GnaneswaraReddy_INFO5731_Fall2024/blob/main/Palem_Gnaneswara_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of Friday, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

## Question 1 (10 Points)
Describe an interesting **text classification or text mining task** and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features. **Your dataset must be text.**

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:
Task: Sentiment Analysis
Useful features to buld machne learnng model:
1. Bag of Words: it is a representation of text data, where each word in the text is represented as a feature.
2. N-grams: N-grams are sequences of n-consecutive words.
3. Parts of speech Tags: This method assigns each word in the text to a part of speech tag, such as noun, verb, adjective, etc.
4. Sentiment Lexicon sores: These are predefined dictionaries that associate with sentiment scores.
5. Text readability and length features: These features are used to signal the extremity of the expressed sentiment.




'''

## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [ ]:
# You code here (Please add comments in the code):
!pip install nltk scikit-learn textblob

In [ ]:
#importing required libraries
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from textblob import TextBlob
from nltk import pos_tag, word_tokenize
from nltk.corpus import sentiwordnet as swn
from textblob import TextBlob
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.util import ngrams
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize

In [ ]:
#Downloading NTLK data
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
nltk.download('sentiwordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package sentiwordnet to /root/nltk_data...
[nltk_data]   Package sentiwordnet is already up-to-date!


True

In [ ]:
#sample input text
texts = [
    "I absolutely love this product! It works like a charm and exceeded my expectations.",
    "This is the worst experience I've ever had. Terrible service and awful product.",
    "The product is okay. Nothing special but does the job.",
    "I'm not sure if I like this. It's not what I expected but it's not terrible either."
]


In [ ]:
#1. Bag of Words
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(texts)
print("Bag of Words Features:\n", bow_matrix.toarray())
print("BoW Vocabulary:\n", vectorizer.get_feature_names_out())

#2. N-grams
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))
bigram_matrix = bigram_vectorizer.fit_transform(texts)
print("\nBigrams Features:\n", bigram_matrix.toarray())
print("Bigram Vocabulary:\n", bigram_vectorizer.get_feature_names_out())

#3. POS Tagging
pos_tags = [pos_tag(word_tokenize(text)) for text in texts]
print("\nPart of Speech Tags:\n", pos_tags)

#4. Sentiment Lexicon Scores using TextBlob
for text in texts:
    blob = TextBlob(text)
    sentiment = blob.sentiment.polarity  # Sentiment polarity score from -1 (negative) to +1 (positive)
    print(f"\nText: '{text}'")
    print(f"Sentiment Score: {sentiment}")

#5. Text Readability and Length-Based Features
for text in texts:
    num_sentences = len(sent_tokenize(text))
    num_words = len(word_tokenize(text))
    avg_word_length = sum(len(word) for word in word_tokenize(text)) / num_words
    print(f"\nText: '{text}'")
    print(f"Number of Sentences: {num_sentences}")
    print(f"Number of Words: {num_words}")
    print(f"Average Word Length: {avg_word_length:.2f}")

Bag of Words Features:
 [[1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0]
 [0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1]
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 0 2 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 2 0 1 0 0 3 0 0 0 0 0 1 1 0 1 0 1 0 0]]
BoW Vocabulary:
 ['absolutely' 'and' 'awful' 'but' 'charm' 'does' 'either' 'ever'
 'exceeded' 'expectations' 'expected' 'experience' 'had' 'if' 'is' 'it'
 'job' 'like' 'love' 'my' 'not' 'nothing' 'okay' 'product' 'service'
 'special' 'sure' 'terrible' 'the' 'this' 've' 'what' 'works' 'worst']

Bigrams Features:
 [[1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 1 0 0 1 0]
 [0 1 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0
  1 1 0 0 1 0 0 1]
 [0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1
  0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 2 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0
  0 0 1 0 0 1 0 0]]
Bigr

## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [ ]:
#I am using t-test based method
# You code here (Please add comments in the code):
#importing required libraries
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from scipy.stats import ttest_ind

# Sample iput text
texts = [
    "I absolutely love this product! It works like a charm and exceeded my expectations.",  # positive
    "This is the worst experience I've ever had. Terrible service and awful product.",       # negative
    "The product is okay. Nothing special but does the job.",                               # neutral
    "I'm not sure if I like this. It's not what I expected but it's not terrible either."    # neutral
]

# Target labels: 1 = positive, 0 = negative, 2 = neutral
labels = [1, 0, 2, 2]

# Extracting Bag of Words features
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(texts)

feature_names = np.array(vectorizer.get_feature_names_out())

labels = np.array(labels)

# sepearting the text into two groups
group1 = bow_matrix[labels != 2].toarray()
group2 = bow_matrix[labels == 2].toarray()

# performing the t-test
t_scores, p_values = ttest_ind(group1, group2, axis=0)

# Ranking features in descending order
sorted_indices = np.argsort(np.abs(t_scores))[::-1]
top_features = feature_names[sorted_indices]
top_t_scores = t_scores[sorted_indices]

# Displayng the most important features with their t-test scores
print("Top Features Ranked by T-Test Scores:")
for i in range(len(top_features)):
    print(f"Feature: {top_features[i]}, T-Score: {top_t_scores[i]:.2f}")





Top Features Ranked by T-Test Scores:
Feature: and, T-Score: inf
Feature: but, T-Score: -inf
Feature: worst, T-Score: 1.00
Feature: works, T-Score: 1.00
Feature: awful, T-Score: 1.00
Feature: charm, T-Score: 1.00
Feature: does, T-Score: -1.00
Feature: either, T-Score: -1.00
Feature: ever, T-Score: 1.00
Feature: exceeded, T-Score: 1.00
Feature: expectations, T-Score: 1.00
Feature: expected, T-Score: -1.00
Feature: experience, T-Score: 1.00
Feature: had, T-Score: 1.00
Feature: if, T-Score: -1.00
Feature: job, T-Score: -1.00
Feature: service, T-Score: 1.00
Feature: product, T-Score: 1.00
Feature: what, T-Score: -1.00
Feature: ve, T-Score: 1.00
Feature: this, T-Score: 1.00
Feature: sure, T-Score: -1.00
Feature: special, T-Score: -1.00
Feature: love, T-Score: 1.00
Feature: absolutely, T-Score: 1.00
Feature: okay, T-Score: -1.00
Feature: nothing, T-Score: -1.00
Feature: not, T-Score: -1.00
Feature: my, T-Score: 1.00
Feature: the, T-Score: -0.45
Feature: it, T-Score: -0.45
Feature: terrible, 

## Question 4 (10 points):
Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [ ]:
# You code here (Please add comments in the code):
import torch
from transformers import BertTokenizer, BertModel
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Load pre-trained BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Sample input text
texts = [
    "I absolutely love this product! It works like a charm and exceeded my expectations.",
    "This is the worst experience I've ever had. Terrible service and awful product.",
    "The product is okay. Nothing special but does the job.",
    "I'm not sure if I like this. It's not what I expected but it's not terrible either."
]

# query that matches relevant documents
query = "I really like this product and it exceeded my expectations."

# Function for computing BERT embeddings
def get_bert_embedding(text):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=512)

    with torch.no_grad():
        outputs = model(**inputs)
        # Use the [CLS] token's representation as the sentence embedding
        cls_embedding = outputs.last_hidden_state[:, 0, :]

    return cls_embedding

# Compute embeddings for all texts and the query
query_embedding = get_bert_embedding(query)

text_embeddings = []
for text in texts:
    embedding = get_bert_embedding(text)
    text_embeddings.append(embedding)

query_embedding_np = query_embedding.cpu().numpy()
text_embeddings_np = [embedding.cpu().numpy() for embedding in text_embeddings]

# Calculate cosine similarity between the query and each document
cosine_similarities = [cosine_similarity(query_embedding_np, text_embedding)[0][0] for text_embedding in text_embeddings_np]

# Rank the documents by similarity score (descending order)
ranked_indices = np.argsort(cosine_similarities)[::-1]
ranked_texts = [texts[i] for i in ranked_indices]
ranked_similarities = [cosine_similarities[i] for i in ranked_indices]

# Displaying the ranked documents with their similarity scores in descending order
print("Ranked Documents based on Cosine Similarity with Query:")
for i, (text, similarity) in enumerate(zip(ranked_texts, ranked_similarities)):
    print(f"Rank {i+1}:")
    print(f"Text: '{text}'")
    print(f"Cosine Similarity: {similarity:.4f}")
    print("-" * 80)





/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


Ranked Documents based on Cosine Similarity with Query:
Rank 1:
Text: 'I absolutely love this product! It works like a charm and exceeded my expectations.'
Cosine Similarity: 0.9783
--------------------------------------------------------------------------------
Rank 2:
Text: 'I'm not sure if I like this. It's not what I expected but it's not terrible either.'
Cosine Similarity: 0.9000
--------------------------------------------------------------------------------
Rank 3:
Text: 'This is the worst experience I've ever had. Terrible service and awful product.'
Cosine Similarity: 0.8702
--------------------------------------------------------------------------------
Rank 4:
Text: 'The product is okay. Nothing special but does the job.'
Cosine Similarity: 0.8397
--------------------------------------------------------------------------------


# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:
I found the first question as a good challenge to me, where I took "Sentiment Analysis" as a text classifiction task.
I have also disscussed some features such as Bag of Words (BoW), N-grams, POS tagging, sentiment lexicon scores, and text readability.
I also explored feature extraction techniques such as Bag of Words, TF-IDF, and word embeddings, including using BERT.
Understanding how these methods convert raw text into numerical representations was crucial.
Learning to calculate cosine similarity using BERT embeddings provided practical insight into comparing the semantic similarity of texts.
Working on extracting features from text data was an enriching experience that enhanced my understanding of Natural Language Processing (NLP).




'''